### ISSUE TITLE
Consider mentioning how to handle the dependency in setup.py

### ISSUE THREAD

**Issue by shaypal5** [rbarrois/restricted_pkg#6]
Hey Raphael!

First of all, great little package! I just started using it to enforce inner-company Python package uploads to our private Pypi server only.

I noticed that pip installing these packages fails for people who don't already have restricted_pkg installed, so I added this code snippet before importing it on `setup.py`:

`BASHCOMMAND = "pip install restricted_pkg"`
`PROCESS = subprocess.Popen(BASHCOMMAND.split(), stdout=subprocess.PIPE)`
`OUTPUT, ERROR = PROCESS.communicate()`

I thought it might be worth mentioning the subject generally, or even give a specific solution, as some people may find this non-trivial.

Cheers,
Shay

**Comment by rbarrois** [comment]
Thanks for the input :)

However, we're not using this project anymore, since this is now natively supported in setuptools: our setup.cfg holds:

```ini
# setup.cfg
[register]
repository = https://pypi.example.org/

[upload]
repository = https://pypi.example.org/

[upload_docs]
repository = https://pypi.example.org/
```

I can't find references to point users to, though :/

**Comment by shaypal5** [comment]
Oh, cool!

Why not add a mention at the repository's README, then?
It will be highly visible...

**Comment by rbarrois** [comment]
Excellent point! I've updated the docs ;)

**Comment by shaypal5** [comment]
Thanks! I moved to using the way you showed me here. It's simple and works like a charm. :)

Our inner Pypi server is a hit. :)
